name: Beego

on:
  push:
    branches: [ master ]
jobs:
  build-ubuntu:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: install beego
        run: |
          rm go.mod
          rm go.sum
          go get github.com/beego/bee
          bee pack
